package com.example.ui.localization

import com.example.domain.model.AppLanguage

data class AppStrings(
  val appName: String,
  val tagline: String,
  val greeting: String,
  val greetingSubtitle: String,
  val settingsTitle: String,
  val newChat: String,
  val inputPlaceholder: String,
  val thinking: String,
  val send: String,
  val voiceInput: String,
  val attachFile: String,
  val clearChat: String,
  val suggestionsHeader: String,
  val suggestions: List<String>,

  // Voice Assistant Strings
  val voiceModeTitle: String,
  val voiceListening: String,
  val voiceThinking: String,
  val voiceSpeaking: String,
  val voiceIdlePrompt: String,
  val voiceInputOption: String,
  val autoSendOption: String,
  val speakAiResponsesOption: String,
  val speechRateOption: String,
  val voiceLanguageOption: String,
  val stopSpeakingAction: String,
  val micPermissionRequiredMessage: String,
  val openSettingsAction: String,
  val cancelAction: String,
  val tapToSpeakPrompt: String,
  val speechUnavailableNotice: String,

  // Settings
  val languageCategory: String,
  val languageSubtitle: String,
  val appearanceCategory: String,
  val appearanceSubtitle: String,
  val darkThemeLabel: String,
  val voiceCategory: String,
  val voiceSubtitle: String,
  val voiceEnabledLabel: String,
  val aiCategory: String,
  val aiSubtitle: String,
  val memoryCategory: String,
  val memorySubtitle: String,
  val memoryEnabledLabel: String,
  val permissionsCategory: String,
  val permissionsSubtitle: String,
  val micPermissionLabel: String,
  val storagePermissionLabel: String,
  val aboutCategory: String,
  val aboutSubtitle: String,
  val versionLabel: String,
  val developerLabel: String,
  val statusActive: String,
  val statusPlaceholder: String,
  val back: String,

  // Smart System Tools & Actions
  val systemActionsTitle: String,
  val calendarEventLabel: String,
  val alarmLabel: String,
  val timerLabel: String,
  val flashlightLabel: String,
  val silentModeLabel: String,
  val brightnessLabel: String,
  val actionCompleted: String,
  val actionIntentLaunched: String,
  val actionPermissionRequired: String,
  val grantPermissionAction: String,
  val openAppAction: String,
  val openCalendarAction: String,
  val openAlarmAction: String,
  val toggleFlashlightAction: String,
  val retryAction: String,

  // Creative Studio
  val creativeStudioTitle: String,
  val creativeStudioTagline: String,
  val tabCreateImage: String,
  val tabCreateVideo: String,
  val tabEditImage: String,
  val tabSocialMedia: String,
  val tabCreativeHistory: String,
  val promptLabel: String,
  val imagePromptPlaceholder: String,
  val videoPromptPlaceholder: String,
  val editInstructionPlaceholder: String,
  val socialTopicPlaceholder: String,
  val improvePromptToggle: String,
  val enhancedPromptLabel: String,
  val styleLabel: String,
  val aspectRatioLabel: String,
  val durationLabel: String,
  val selectImageAction: String,
  val generateAction: String,
  val regenerateAction: String,
  val saveToGalleryAction: String,
  val shareAction: String,
  val editAction: String,
  val useAsReferenceAction: String,
  val emptyHistoryTitle: String,
  val emptyHistorySubtitle: String,
  val savedSuccessNotice: String,
  val savedFailNotice: String,
  val configRequiredNotice: String,
  val platformLabel: String,
  val formatLabel: String,
  val generateSocialAction: String,
  val visualConceptTitle: String,
  val captionTitle: String,
  val hashtagsTitle: String,
  val scriptTitle: String,
  val useInImageStudioAction: String,
  val useInVideoStudioAction: String,
  val engineLabel: String,
  val engineUnlimitedLabel: String,
  val engineUnlimitedSubtitle: String,
  val engineGeminiLabel: String,
  val engineGeminiSubtitle: String,
  val unlimitedModeBadge: String,
  val unlimitedModeNotice: String,

  // Gemini API Key & Direct In-App Activation
  val geminiKeySectionTitle: String,
  val geminiKeySectionSubtitle: String,
  val geminiKeyInputLabel: String,
  val geminiKeyPlaceholder: String,
  val geminiKeyStatusActive: String,
  val geminiKeyStatusInactive: String,
  val geminiKeyActivateAction: String,
  val geminiKeyTestAction: String,
  val geminiKeyRemoveAction: String,
  val geminiKeyChangeAction: String,
  val geminiKeyPasteAction: String,
  val geminiKeyGetFreeKeyHelp: String,
  val geminiKeySuccessNotice: String,
  val geminiKeyInvalidNotice: String,
  val geminiKeyTestingNotice: String,
  val geminiKeyHelpDescription: String,

  // Background Voice Assistant ("سڵاو باسۆ")
  val bgVoiceCategory: String,
  val bgVoiceSubtitle: String,
  val bgVoiceEnableLabel: String,
  val bgVoiceActiveStatus: String,
  val bgVoiceInactiveStatus: String,
  val bgVoiceExplanation: String,
  val bgVoiceWakeWordHint: String,
  val bgVoiceQuickTestAction: String
)

object LocalizedStrings {

  private val kurdish = AppStrings(
    appName = "Baso AI",
    tagline = "یاریدەدەری زیرەکی تایبەتیت",
    greeting = "سڵاو 👋 من Baso AI ـم.\nچۆن دەتوانم یارمەتیت بدەم؟",
    greetingSubtitle = "ئامادەم بۆ وەڵامدانەوەی پرسیارەکانت، داڕشتنی بیرۆکە، و ڕێکخستنی کارەکانت.",
    settingsTitle = "ڕێکخستنەکان",
    newChat = "گفتوگۆی نوێ",
    inputPlaceholder = "پەیامێک بنووسە بۆ Baso AI...",
    thinking = "بیر دەکەمەوە... 🧠",
    send = "ناردن",
    voiceInput = "دەنگ",
    attachFile = "پێوەکراو",
    clearChat = "سڕینەوەی چات",
    suggestionsHeader = "دەستپێکە پێشنیارکراوەکان:",
    suggestions = listOf(
      "سڵاو باسۆ وایفای دابخە 📶",
      "فلاش دابگیرسێنە 🔦",
      "مۆبایلەکەم بێدەنگ بکە 🔕",
      "کاتژمێر 7 ی بەیانی زەنگم بۆ لێدە ⏰"
    ),

    // Voice Assistant Strings
    voiceModeTitle = "دۆخی دەنگی Baso",
    voiceListening = "گوێم لێیە... 🎤",
    voiceThinking = "بیر دەکەمەوە... 🧠",
    voiceSpeaking = "قسە دەکەم... 🔊",
    voiceIdlePrompt = "چۆن دەتوانم یارمەتیت بدەم؟",
    voiceInputOption = "هاتنەناوەی دەنگ (Voice Input)",
    autoSendOption = "ناردنی خۆکار دوای قسەکردن",
    speakAiResponsesOption = "خوێندنەوەی وەڵامەکان بە دەنگ",
    speechRateOption = "خێرایی خوێندنەوەی دەنگ",
    voiceLanguageOption = "زمانی ئاخاوتنی دەنگ",
    stopSpeakingAction = "وەستاندنی دەنگ",
    micPermissionRequiredMessage = "بۆ بەکارهێنانی دەنگ، پێویستە مۆڵەتی Microphone بدەیت.",
    openSettingsAction = "ڕێکخستنەکانی ئەپ",
    cancelAction = "پەشیمانبوونەوە",
    tapToSpeakPrompt = "لێبدە بۆ قسەکردن",
    speechUnavailableNotice = "خزمەتگوزاری خوێندنەوەی دەنگی کوردی بەردەست نییە لەم ئامێرەدا؛ بە عەرەبی/ئینگلیزی وەڵام دەدرێتەوە.",

    languageCategory = "زمان",
    languageSubtitle = "دیاریکردنی زمانی کارکردنی ئەپڵیکەیشن",
    appearanceCategory = "ڕووکار",
    appearanceSubtitle = "شێوازی پیشاندانی ڕەنگ و دۆخی تاریک",
    darkThemeLabel = "دۆخی تاریک (Dark Mode)",
    voiceCategory = "دەنگ و گفتوگۆ",
    voiceSubtitle = "ئاخاوتنی دەنگی، وەرگێڕانی قسە، و خوێندنەوەی وەڵامەکان",
    voiceEnabledLabel = "وەڵامدانەوە بە دەنگ",
    aiCategory = "مۆدێلی ژیریی دەستکرد",
    aiSubtitle = "بەستنەوە بە Google Gemini و خێرایی",
    memoryCategory = "بیرگە و یادگە",
    memorySubtitle = "پاراستنی زانیاری و ئارەزووە کەسییەکانت",
    memoryEnabledLabel = "چالاککردنی بیرگەی درێژخایەن",
    permissionsCategory = "مۆڵەتەکان",
    permissionsSubtitle = "مایکرۆفۆن، پەڕگەکان، و پێداویستییەکان",
    micPermissionLabel = "مۆڵەتی مایکرۆفۆن",
    storagePermissionLabel = "مۆڵەتی بیرگە و پەڕگە",
    aboutCategory = "دەربارەی Baso AI",
    aboutSubtitle = "زانیاری وەشان و مافەکان",
    versionLabel = "وەشان: 1.1 (Voice Assistant)",
    developerLabel = "دروستکراوە بۆ داهاتوویەکی زیرەکتر",
    statusActive = "چالاکە",
    statusPlaceholder = "ئامادەکاری بۆ وەشانەکانی داهاتوو",
    back = "گەڕانەوە",

    // Smart System Tools & Actions
    systemActionsTitle = "کردارە زیرەکەکانی سیستەم",
    calendarEventLabel = "تۆماری ڕۆژمێر",
    alarmLabel = "زەنگی کاتژمێر",
    timerLabel = "تایمەر",
    flashlightLabel = "فلاشی کامێرا",
    silentModeLabel = "دۆخی بێدەنگ",
    brightnessLabel = "ڕووناکی شاشە",
    actionCompleted = "جێبەجێکرا",
    actionIntentLaunched = "کرایەوە لە سیستەم",
    actionPermissionRequired = "مۆڵەت پێویستە",
    grantPermissionAction = "پێدانی مۆڵەت",
    openAppAction = "کردنەوەی ئەپ",
    openCalendarAction = "کردنەوەی ڕۆژمێر",
    openAlarmAction = "کردنەوەی کاتژمێر",
    toggleFlashlightAction = "گۆڕینی فلاش",
    retryAction = "دووبارەکردنەوە",

    // Creative Studio
    creativeStudioTitle = "ستۆدیۆی داهێنان",
    creativeStudioTagline = "دروستکردنی وێنە، ڤیدیۆ و تۆڕە کۆمەڵایەتییەکان بە ژیری دەستکرد",
    tabCreateImage = "دروستکردنی وێنە",
    tabCreateVideo = "دروستکردنی ڤیدیۆ",
    tabEditImage = "دەستکاریکردنی وێنە",
    tabSocialMedia = "تۆڕە کۆمەڵایەتییەکان",
    tabCreativeHistory = "مێژووی داهێنان",
    promptLabel = "داواکاری / وەسفی داهێنان",
    imagePromptPlaceholder = "وەسفی وێنەکە بنووسە... (نموونە: دیمەنێکی ئێوارەی شاری هەولێر بە ستایلی سینەمایی)",
    videoPromptPlaceholder = "وەسفی ڤیدیۆکە بنووسە... (نموونە: دیمەنێکی فڕۆکە لە چیاکانی کوردستان)",
    editInstructionPlaceholder = "ڕێنمایی دەستکاریکردن بنووسە... (نموونە: باکگراوەند بگۆڕە بۆ مۆدێرن)",
    socialTopicPlaceholder = "بیرۆکەی پۆستەکەت بنووسە... (نموونە: گرنگی تەکنەلۆژیا بۆ فێربوون)",
    improvePromptToggle = "✨ باشترکردنی داواکاری بە AI",
    enhancedPromptLabel = "داواکاری باشترکراوی Baso:",
    styleLabel = "شێواز و ستایل",
    aspectRatioLabel = "ڕێژەی ڕوونما (قەبارە)",
    durationLabel = "ماوەی ڤیدیۆ",
    selectImageAction = "هەڵبژاردنی وێنە",
    generateAction = "دروستکردن",
    regenerateAction = "دووبارە دروستکردنەوە",
    saveToGalleryAction = "پاشەکەوت لە گەلەری",
    shareAction = "هاوبەشکردن",
    editAction = "دەستکاریکردن",
    useAsReferenceAction = "بەکارهێنان بۆ ڤیدیۆ",
    emptyHistoryTitle = "هیچ پرۆژەیەکی داهێنان نییە",
    emptyHistorySubtitle = "هەر وێنە، ڤیدیۆ یان پۆستێک دروست بکەیت لێرە دەپارێزرێت.",
    savedSuccessNotice = "بە سەرکەوتوویی لە گەلەری پاشەکەوت کرا",
    savedFailNotice = "پاشەکەوتکردن سەرکەوتوو نەبوو",
    configRequiredNotice = "پێویستی بە ڕێکخستنی کلیل هەیە لە Google AI Studio",
    platformLabel = "پلاتفۆرمی تۆڕی کۆمەڵایەتی",
    formatLabel = "شێوازی بڵاوکردنەوە",
    generateSocialAction = "دروستکردنی پاکێجی پۆست",
    visualConceptTitle = "چەمکی وێنە و دیمەن",
    captionTitle = "دەقی پۆست (Caption)",
    hashtagsTitle = "هاشتاگەکان",
    scriptTitle = "سکریپتی کورت",
    useInImageStudioAction = "ناردن بۆ دروستکردنی وێنە",
    useInVideoStudioAction = "ناردن بۆ دروستکردنی ڤیدیۆ",
    engineLabel = "مۆدێلی بەرهەمهێنان:",
    engineUnlimitedLabel = "مۆدی بێسنوور (Unlimited AI)",
    engineUnlimitedSubtitle = "بێسنوور و خێرا بەبێ کوۆتا",
    engineGeminiLabel = "گووگڵ جێمینای (Gemini Flash)",
    engineGeminiSubtitle = "مۆدێلی وێنەی فەرمی جێمینای",
    unlimitedModeBadge = "⚡ بێسنوور چالاکە",
    unlimitedModeNotice = "داواکاری بێسنوورە و هیچ سنوردارکردنێکی ڕێژە نییە",

    // Gemini API Key & Direct In-App Activation
    geminiKeySectionTitle = "کلیلی Gemini و ئاکتیڤکردن",
    geminiKeySectionSubtitle = "دانانی کلیلی تایبەت ڕاستەوخۆ لەناو ئەپ بۆ کارپێکردنی تەواوی زیرەکی دەستکرد",
    geminiKeyInputLabel = "کلیلی Gemini API (GEMINI_API_KEY)",
    geminiKeyPlaceholder = "AIzaSy...",
    geminiKeyStatusActive = "ئاکتیڤ کراوە (چالاکە) ✅",
    geminiKeyStatusInactive = "ناچالاکە (پێویستی بە کلیلە) ⚠️",
    geminiKeyActivateAction = "ئاکتیڤ کردن",
    geminiKeyTestAction = "تاقیکردنەوەی کلیل",
    geminiKeyRemoveAction = "ناچالاککردن و سڕینەوە",
    geminiKeyChangeAction = "گۆڕینی کلیل",
    geminiKeyPasteAction = "لکاندن (Paste)",
    geminiKeyGetFreeKeyHelp = "وەرگرتنی کلیلی بێبەرامبەر لە Google AI Studio (aistudio.google.com)",
    geminiKeySuccessNotice = "کلیلەکە بە سەرکەوتوویی ئاکتیڤ کرا و بەستراوەتەوە!",
    geminiKeyInvalidNotice = "کلیلەکە هەڵەیە یان پەیوەندی دروست نەبوو، تکایە کلیلەکەت بپشکنە.",
    geminiKeyTestingNotice = "لە تاقیکردنەوەی کلیلەکەیە لەگەڵ سێرڤەری گووگڵ...",
    geminiKeyHelpDescription = "بە دانانی کلیلی Gemini دەتوانیت مۆدێلە پێشکەوتووەکانی Gemini 3.5 Flash، چاتی زیرەکی خێرا، دەستکاریکردنی وێنە و دروستکردنی ڤیدیۆ بەکاربهێنیت.",

    // Background Voice Assistant ("سڵاو باسۆ")
    bgVoiceCategory = "یاریدەدەری دەنگی لە باکگراوند (سڵاو باسۆ)",
    bgVoiceSubtitle = "گوێگرتن و وەڵامدانەوە تەنانەت ئەگەر ئەپەکە داخراو بێت",
    bgVoiceEnableLabel = "چالاککردنی خزمەتگوزاری پاشبنەما",
    bgVoiceActiveStatus = "چالاکە لە پاشبنەما (سڵاو باسۆ بڵێ) 🎙️",
    bgVoiceInactiveStatus = "ناچالاکە ⚪",
    bgVoiceExplanation = "کاتێک ئەم خزمەتگوزارییە چالاکە، دەتوانیت لە هەر کاتێکدا (تەنانەت ئەگەر شاشەکە داخراو بێت یان لە ئەپێکی تردا بیت) بڵێیت «سڵاو باسۆ» بۆ جێبەجێکردنی فەرمانەکانی وەک: کردنەوەی پەنجەرەی وایفای، داگیرساندنی فلاش، دانانی زەنگ و تایمەر، یان کردنەوەی ئەپەکان.",
    bgVoiceWakeWordHint = "وشەی دەستپێکردن: «سڵاو باسۆ» یان «سڵاو باسۆ وایفای دابخە»",
    bgVoiceQuickTestAction = "تاقیکردنەوەی خێرا"
  )

  private val arabic = AppStrings(
    appName = "Baso AI",
    tagline = "مساعدك الشخصي الذكي",
    greeting = "مرحباً 👋 أنا Baso AI.\nكيف يمكنني مساعدتك اليوم؟",
    greetingSubtitle = "مستعد للإجابة عن أسئلتك، صياغة أفكارك وتنظيم مهامك.",
    settingsTitle = "الإعدادات",
    newChat = "محادثة جديدة",
    inputPlaceholder = "اكتب رسالة إلى Baso AI...",
    thinking = "جارِ التفكير... 🧠",
    send = "إرسال",
    voiceInput = "صوت",
    attachFile = "مرفق",
    clearChat = "مسح المحادثة",
    suggestionsHeader = "اقتراحات للبدء:",
    suggestions = listOf(
      "سجل اجتماع غداً الساعة 10 📅",
      "شغل الفلاش 🔦",
      "الوضع الصامت 🔕",
      "اضبط منبه الساعة 7 صباحاً ⏰"
    ),

    // Voice Assistant Strings
    voiceModeTitle = "الوضع الصوتي Baso",
    voiceListening = "أنا أستمع إليك... 🎤",
    voiceThinking = "جارِ التفكير... 🧠",
    voiceSpeaking = "أتحدث الآن... 🔊",
    voiceIdlePrompt = "كيف يمكنني مساعدتك؟",
    voiceInputOption = "الإدخال الصوتي (Voice Input)",
    autoSendOption = "إرسال تلقائي بعد التحدث",
    speakAiResponsesOption = "نطق ردود المساعد صوتياً",
    speechRateOption = "سرعة نطق الصوت",
    voiceLanguageOption = "لغة الإدخال الصوتي",
    stopSpeakingAction = "إيقاف الصوت",
    micPermissionRequiredMessage = "لاستخدام الصوت، يجب منح إذن الميكروفون.",
    openSettingsAction = "إعدادات التطبيق",
    cancelAction = "إلغاء",
    tapToSpeakPrompt = "اضغط للتحدث",
    speechUnavailableNotice = "الصوت الكردي غير مثبت في الجهاز؛ سيتم النطق بالصوت البديل المتاح.",

    languageCategory = "اللغة",
    languageSubtitle = "تحديد لغة واجهة التطبيق",
    appearanceCategory = "المظهر",
    appearanceSubtitle = "السمة والألوان والوضع الليلي",
    darkThemeLabel = "الوضع الداكن (Dark Mode)",
    voiceCategory = "الصوت والتحدث",
    voiceSubtitle = "المساعد الصوتي ونطق الردود وتحويل الكلام لنص",
    voiceEnabledLabel = "تفعيل الصوت التفاعلي",
    aiCategory = "نموذج الذكاء الاصطناعي",
    aiSubtitle = "التكامل مع Google Gemini والسرعة",
    memoryCategory = "الذاكرة الشخصية",
    memorySubtitle = "تذكر التفضيلات والبيانات الخاصة بك",
    memoryEnabledLabel = "تفعيل الذاكرة طويلة المدى",
    permissionsCategory = "الأذونات",
    permissionsSubtitle = "الميكروفون، الملفات والنظام",
    micPermissionLabel = "إذن الميكروفون",
    storagePermissionLabel = "إذن الملفات والتخزين",
    aboutCategory = "حول Baso AI",
    aboutSubtitle = "معلومات الإصدار والحقوق",
    versionLabel = "الإصدار: 1.1 (Voice Assistant)",
    developerLabel = "مصمم لمستقبل رقمي أكثر ذكاءً",
    statusActive = "مفعّل",
    statusPlaceholder = "جاهز للتحديثات القادمة",
    back = "رجوع",

    // Smart System Tools & Actions
    systemActionsTitle = "أدوات النظام الذكية",
    calendarEventLabel = "حدث التقويم",
    alarmLabel = "منبه الهاتف",
    timerLabel = "المؤقت",
    flashlightLabel = "فلاش الكاميرا",
    silentModeLabel = "الوضع الصامت",
    brightnessLabel = "سطوع الشاشة",
    actionCompleted = "تم التنفيذ",
    actionIntentLaunched = "تم الفتح في النظام",
    actionPermissionRequired = "الإذن مطلوب",
    grantPermissionAction = "منح الإذن",
    openAppAction = "فتح التطبيق",
    openCalendarAction = "فتح التقويم",
    openAlarmAction = "فتح المنبه",
    toggleFlashlightAction = "تبديل الفلاش",
    retryAction = "إعادة المحاولة",

    // Creative Studio
    creativeStudioTitle = "استوديو الإبداع",
    creativeStudioTagline = "توليد الصور والفيديوهات ومحتوى التواصل بالذكاء الاصطناعي",
    tabCreateImage = "إنشاء صورة",
    tabCreateVideo = "إنشاء فيديو",
    tabEditImage = "تعديل صورة",
    tabSocialMedia = "التواصل الاجتماعي",
    tabCreativeHistory = "سجل الإبداع",
    promptLabel = "الوصف / طلب التوليد",
    imagePromptPlaceholder = "اكتب وصف الصورة بالتفصيل... (مثال: مشهد سينمائي لمدينة أربيل عند الغروب)",
    videoPromptPlaceholder = "اكتب وصف الفيديو المطلوب... (مثال: لقطة درون فوق الجبال الخضراء)",
    editInstructionPlaceholder = "اكتب تعليمات تعديل الصورة... (مثال: تغيير الخلفية إلى شاطئ بحر)",
    socialTopicPlaceholder = "اكتب فكرة أو موضوع المنشور... (مثال: أهمية الذكاء الاصطناعي في التعليم)",
    improvePromptToggle = "✨ تحسين الطلب بالذكاء الاصطناعي",
    enhancedPromptLabel = "طلب التوليد المحسّن من Baso:",
    styleLabel = "النمط والأسلوب",
    aspectRatioLabel = "أبعاد الشاشة (النسبة)",
    durationLabel = "مدة الفيديو",
    selectImageAction = "اختيار صورة",
    generateAction = "توليد",
    regenerateAction = "إعادة التوليد",
    saveToGalleryAction = "حفظ في المعرض",
    shareAction = "مشاركة",
    editAction = "تعديل",
    useAsReferenceAction = "استخدام كمرجع للفيديو",
    emptyHistoryTitle = "لا توجد مشاريع إبداعية",
    emptyHistorySubtitle = "سيتم حفظ أي صورة أو فيديو أو منشور يتم إنشاؤه هنا.",
    savedSuccessNotice = "تم الحفظ في المعرض بنجاح",
    savedFailNotice = "فشل في الحفظ",
    configRequiredNotice = "يتطلب ضبط مفتاح Google AI Studio",
    platformLabel = "منصة التواصل",
    formatLabel = "نوع المحتوى",
    generateSocialAction = "إنشاء حزمة المنشور",
    visualConceptTitle = "المفهوم البصري",
    captionTitle = "نص المنشور (الكابشن)",
    hashtagsTitle = "الهاشتاغات",
    scriptTitle = "سيناريو قصير",
    useInImageStudioAction = "إرسال إلى استوديو الصور",
    useInVideoStudioAction = "إرسال إلى استوديو الفيديو",
    engineLabel = "محرك التوليد:",
    engineUnlimitedLabel = "الوضع اللامحدود (Unlimited AI)",
    engineUnlimitedSubtitle = "توليد فوري بلا قيود أو حصص",
    engineGeminiLabel = "جوجل جيميني (Gemini Flash)",
    engineGeminiSubtitle = "نموذج صور جيميني الرسمي",
    unlimitedModeBadge = "⚡ الوضع اللامحدود مفعّل",
    unlimitedModeNotice = "يمكنك التوليد بلا حدود للحصة اليومية",

    // Gemini API Key & Direct In-App Activation
    geminiKeySectionTitle = "مفتاح Gemini والتفعيل",
    geminiKeySectionSubtitle = "إدخال المفتاح مباشرة داخل التطبيق لتفعيل الذكاء الاصطناعي",
    geminiKeyInputLabel = "مفتاح Gemini API (GEMINI_API_KEY)",
    geminiKeyPlaceholder = "AIzaSy...",
    geminiKeyStatusActive = "مُفعَّل (نشط) ✅",
    geminiKeyStatusInactive = "غير مفعَّل (يتطلب مفتاح) ⚠️",
    geminiKeyActivateAction = "تفعيل",
    geminiKeyTestAction = "اختبار المفتاح",
    geminiKeyRemoveAction = "تعطيل وحذف",
    geminiKeyChangeAction = "تغيير المفتاح",
    geminiKeyPasteAction = "لصق (Paste)",
    geminiKeyGetFreeKeyHelp = "الحصول على مفتاح مجاني من Google AI Studio (aistudio.google.com)",
    geminiKeySuccessNotice = "تم تفعيل المفتاح والاتصال بنجاح!",
    geminiKeyInvalidNotice = "المفتاح غير صالح أو فشل الاتصال، يرجى التحقق.",
    geminiKeyTestingNotice = "جارٍ اختبار المفتاح مع خوادم Google...",
    geminiKeyHelpDescription = "بإدخال مفتاح Gemini، ستتمكن من استخدام نماذج Gemini 3.5 Flash، والمحادثة الذكية، وتعديل الصور وتوليد الفيديو.",

    // Background Voice Assistant ("مرحبا باسو")
    bgVoiceCategory = "المساعد الصوتي في الخلفية (سڵاو باسۆ)",
    bgVoiceSubtitle = "الاستماع والتنفيذ المباشر حتى عند إغلاق التطبيق",
    bgVoiceEnableLabel = "تفعيل خدمة الخلفية الدائمة",
    bgVoiceActiveStatus = "نشط في الخلفية (قل: سڵاو باسۆ) 🎙️",
    bgVoiceInactiveStatus = "غير مفعَّل ⚪",
    bgVoiceExplanation = "عند تفعيل هذه الخدمة، يمكنك في أي وقت ومن أي شاشة قول «سڵاو باسۆ» للتحكم في الواي فاي، الفلاش، المنبه، أو فتح التطبيقات.",
    bgVoiceWakeWordHint = "كلمة التنبيه: «سڵاو باسۆ» أو «Hey Baso»",
    bgVoiceQuickTestAction = "اختبار سريع"
  )

  private val english = AppStrings(
    appName = "Baso AI",
    tagline = "Your Smart Personal Assistant",
    greeting = "Hello 👋 I am Baso AI.\nHow can I assist you today?",
    greetingSubtitle = "Ready to answer questions, brainstorm ideas, and organize your tasks.",
    settingsTitle = "Settings",
    newChat = "New Chat",
    inputPlaceholder = "Message Baso AI...",
    thinking = "Thinking... 🧠",
    send = "Send",
    voiceInput = "Voice",
    attachFile = "Attach",
    clearChat = "Clear Chat",
    suggestionsHeader = "Suggested starters:",
    suggestions = listOf(
      "Schedule a meeting tomorrow at 10 am 📅",
      "Turn on flashlight 🔦",
      "Set phone to silent mode 🔕",
      "Set an alarm for 7:00 AM ⏰"
    ),

    // Voice Assistant Strings
    voiceModeTitle = "Baso Voice Mode",
    voiceListening = "Baso is listening... 🎤",
    voiceThinking = "Thinking... 🧠",
    voiceSpeaking = "Speaking... 🔊",
    voiceIdlePrompt = "How can I help you?",
    voiceInputOption = "Voice Input",
    autoSendOption = "Auto-send recognized speech",
    speakAiResponsesOption = "Read AI responses aloud",
    speechRateOption = "Speech speed",
    voiceLanguageOption = "Voice language",
    stopSpeakingAction = "Stop speaking",
    micPermissionRequiredMessage = "Microphone permission is required to use voice input.",
    openSettingsAction = "App Settings",
    cancelAction = "Cancel",
    tapToSpeakPrompt = "Tap to speak",
    speechUnavailableNotice = "Native Kurdish TTS is unavailable on this device; falling back gracefully.",

    languageCategory = "Language",
    languageSubtitle = "Select the app language",
    appearanceCategory = "Appearance",
    appearanceSubtitle = "Dark theme and visual styling",
    darkThemeLabel = "Dark Theme",
    voiceCategory = "Voice & Speech",
    voiceSubtitle = "Speech input, voice assistant & speech synthesis",
    voiceEnabledLabel = "Voice responses enabled",
    aiCategory = "AI Model",
    aiSubtitle = "Google Gemini integration & parameters",
    memoryCategory = "Personal Memory",
    memorySubtitle = "Recall preferences and context",
    memoryEnabledLabel = "Long-term memory enabled",
    permissionsCategory = "Permissions",
    permissionsSubtitle = "Microphone, storage, and system",
    micPermissionLabel = "Microphone permission",
    storagePermissionLabel = "Storage access",
    aboutCategory = "About Baso AI",
    aboutSubtitle = "Version & platform details",
    versionLabel = "Version 1.1 (Voice Assistant)",
    developerLabel = "Engineered for an intelligent future",
    statusActive = "Active",
    statusPlaceholder = "Ready for upcoming modules",
    back = "Back",

    // Smart System Tools & Actions
    systemActionsTitle = "Smart System Actions",
    calendarEventLabel = "Calendar Event",
    alarmLabel = "Alarm",
    timerLabel = "Timer",
    flashlightLabel = "Camera Flashlight",
    silentModeLabel = "Silent Mode",
    brightnessLabel = "Screen Brightness",
    actionCompleted = "Executed",
    actionIntentLaunched = "Launched in System",
    actionPermissionRequired = "Permission Required",
    grantPermissionAction = "Grant Permission",
    openAppAction = "Open App",
    openCalendarAction = "Open Calendar",
    openAlarmAction = "Open Clock",
    toggleFlashlightAction = "Toggle Torch",
    retryAction = "Retry Action",

    // Creative Studio
    creativeStudioTitle = "Creative Studio",
    creativeStudioTagline = "AI Image, Video & Social Content Creation",
    tabCreateImage = "Create Image",
    tabCreateVideo = "Create Video",
    tabEditImage = "Edit Image",
    tabSocialMedia = "Social Media",
    tabCreativeHistory = "History",
    promptLabel = "Prompt / Description",
    imagePromptPlaceholder = "Describe the image you want to create... (e.g., A cinematic sunset over Erbil citadel)",
    videoPromptPlaceholder = "Describe the video you want to generate... (e.g., Drone flyover across green mountains)",
    editInstructionPlaceholder = "Enter image editing instructions... (e.g., Change background to modern cyber city)",
    socialTopicPlaceholder = "Enter post concept or topic... (e.g., AI innovation and the future of work)",
    improvePromptToggle = "✨ Improve my prompt with AI",
    enhancedPromptLabel = "Baso Enhanced Prompt:",
    styleLabel = "Artistic Style",
    aspectRatioLabel = "Aspect Ratio",
    durationLabel = "Video Duration",
    selectImageAction = "Choose Image",
    generateAction = "Generate",
    regenerateAction = "Regenerate",
    saveToGalleryAction = "Save to Gallery",
    shareAction = "Share",
    editAction = "Edit",
    useAsReferenceAction = "Use as Video Reference",
    emptyHistoryTitle = "No Creative Projects",
    emptyHistorySubtitle = "Generated images, videos, and social posts will be stored here.",
    savedSuccessNotice = "Saved to Gallery successfully",
    savedFailNotice = "Failed to save",
    configRequiredNotice = "API key setup required in Google AI Studio Secrets",
    platformLabel = "Social Platform",
    formatLabel = "Post Format",
    generateSocialAction = "Generate Social Package",
    visualConceptTitle = "Visual Concept",
    captionTitle = "Caption",
    hashtagsTitle = "Hashtags",
    scriptTitle = "Short Script",
    useInImageStudioAction = "Send to Image Studio",
    useInVideoStudioAction = "Send to Video Studio",
    engineLabel = "Generation Engine:",
    engineUnlimitedLabel = "Unlimited AI Engine",
    engineUnlimitedSubtitle = "Zero rate limits, unlimited high-res generations",
    engineGeminiLabel = "Google Gemini Flash",
    engineGeminiSubtitle = "Official Gemini multimodal image model",
    unlimitedModeBadge = "⚡ Unlimited Mode Active",
    unlimitedModeNotice = "Unlimited generations with zero quota limits",

    // Gemini API Key & Direct In-App Activation
    geminiKeySectionTitle = "Gemini API Key & Activation",
    geminiKeySectionSubtitle = "Set your key directly in the app to activate AI features",
    geminiKeyInputLabel = "Gemini API Key (GEMINI_API_KEY)",
    geminiKeyPlaceholder = "AIzaSy...",
    geminiKeyStatusActive = "Activated (Active) ✅",
    geminiKeyStatusInactive = "Not Activated (Key Required) ⚠️",
    geminiKeyActivateAction = "Activate Key",
    geminiKeyTestAction = "Test Key",
    geminiKeyRemoveAction = "Deactivate & Remove",
    geminiKeyChangeAction = "Change Key",
    geminiKeyPasteAction = "Paste",
    geminiKeyGetFreeKeyHelp = "Get a free key from Google AI Studio (aistudio.google.com)",
    geminiKeySuccessNotice = "Key successfully verified and activated!",
    geminiKeyInvalidNotice = "Invalid API key or network error. Please verify your key.",
    geminiKeyTestingNotice = "Testing connection with Google Gemini servers...",
    geminiKeyHelpDescription = "Setting your Gemini key activates Gemini 3.5 Flash, intelligent assistant tools, image editing, and video generation.",

    // Background Voice Assistant ("Hey Baso")
    bgVoiceCategory = "Background Voice Assistant (Hey Baso)",
    bgVoiceSubtitle = "Listens and executes commands even when the app is closed",
    bgVoiceEnableLabel = "Enable Background Voice Service",
    bgVoiceActiveStatus = "Active in Background (Say 'سڵاو باسۆ') 🎙️",
    bgVoiceInactiveStatus = "Inactive ⚪",
    bgVoiceExplanation = "When enabled, you can say 'سڵاو باسۆ' or 'Hey Baso' at any time (even when your screen is off or using other apps) to control Wi-Fi, toggle flashlight, set alarms, or open apps.",
    bgVoiceWakeWordHint = "Wake word: 'سڵاو باسۆ' or 'Hey Baso'",
    bgVoiceQuickTestAction = "Quick Test"
  )

  fun get(language: AppLanguage): AppStrings {
    return when (language) {
      AppLanguage.KURDISH_SORANI -> kurdish
      AppLanguage.ARABIC -> arabic
      AppLanguage.ENGLISH -> english
    }
  }
}
